export const dummyJson = {
  approved_practices: [
    {
      hospital_name: 'Care Hospital',
      hospital_area: 'Kondapur',
      hospital_image: null,
      specialization: 'Child Specialist',
      timings: 'Mon to Sat . 10am to 3pm',
      hospital_phone_number: '7780209948',
      hospital_email: 'hospital@gmail.com',
    },
    {
      hospital_name: 'People Care International Hospitals',
      hospital_area: 'Lingampally',
      hospital_image: null,
      specialization: 'Child Specialist',
      timings: 'Mon to Sat . 10am to 3pm',
      hospital_phone_number: '7780209948',
      hospital_email: 'hospital@gmail.com',
    },
    {
      hospital_name: 'Health Care Hospitals',
      hospital_area: 'JNTU',
      hospital_image: null,
      specialization: 'Child Specialist',
      timings: 'Mon to Sat . 10am to 3pm',
      hospital_phone_number: '7780209948',
      hospital_email: 'hospital@gmail.com',
    },
    {
      hospital_name: 'Health Care Hospitals',
      hospital_area: 'JNTU',
      hospital_image: null,
      specialization: 'Child Specialist',
      timings: 'Mon to Sat . 10am to 3pm',
      hospital_phone_number: '7780209948',
      hospital_email: 'hospital@gmail.com',
    },
  ],
  decline_practices: [
    {
      branch_name: 'Yashoda Hospital',
      CITY: 'Panjagutta',
      hospital_image: null,
      specialization: 'Skin Specialist',
      timings: 'Mon to Sat . 10am to 3pm',
      hospital_phone_number: '7780209948',
      hospital_email: 'hospital@gmail.com',
    },
    {
      branch_name: 'Appolo',
      CITY: 'Madhapur',
      hospital_image: null,
      specialization: 'dentist',
      timings: 'Mon to Sat . 10am to 3pm',
      hospital_phone_number: '7780209948',
      hospital_email: 'hospital@gmail.com',
    },
  ],
  requests: [
    {
      hospital_name: 'Yashoda Hospital',
      hospital_area: 'Panjagutta',
      hospital_type: 'Multi specialty Hospital',
      hospital_image: null,
      specialization: 'Skin Specialist',
      working_days: 'Mon to sat',
      timings: '10am to 3pm',
      hospital_phone_number: '7780209948',
      hospital_email: 'hospital@gmail.com',
      appointment_slot_timing: 15,
    },

    {
      hospital_name: 'Appolo Hospital',
      hospital_area: 'Madhapur',
      hospital_type: 'Children Hospital',
      hospital_image: null,
      specialization: 'Doctor',
      working_days: 'Mon to sat',
      timings: '10am to 3pm',
      hospital_phone_number: '7780209948',
      hospital_email: 'hospital@gmail.com',
      appointment_slot_timing: 10,
    },

    {
      hospital_name: 'Gandhi Hospital',
      hospital_area: 'Hyderabad',
      hospital_type: 'General',
      hospital_image: null,
      specialization: 'Heart Specialist',
      working_days: 'Mon to sat',
      timings: '10am to 3pm',
      hospital_phone_number: '7780209948',
      hospital_email: 'hospital@gmail.com',
      appointment_slot_timing: 30,
    },
  ],
  timings: [
    {
      day: 'Monday',
      session1: {
        timings: '9am to 2pm',
        start_time: '9:00',
        end_time: '2:00',
        start_time_text: 'am',
        end_time_text: 'pm',
        in_person_visit: true,
        remote_visit: false,
      },
      session2: {
        timings: '4pm to 8pm',
        in_person_visit: true,
        remote_visit: false,
        start_time: '2:00',
        end_time: '6:00',
        start_time_text: 'pm',
        end_time_text: 'pm',
      },
    },
    {
      day: 'Tuesday',
      session1: {
        timings: '9am to 2pm',
        start_time: '9:00',
        end_time: '2:00',
        start_time_text: 'am',
        end_time_text: 'pm',
        in_person_visit: true,
        remote_visit: false,
      },
      session2: {
        timings: '4pm to 8pm',
        in_person_visit: true,
        remote_visit: true,
        start_time: '2:00',
        end_time: '6:00',
        start_time_text: 'pm',
        end_time_text: 'pm',
      },
    },
    {
      day: 'Wednesday',
      session1: {
        timings: '9am to 2pm',
        start_time: '9:00',
        end_time: '2:00',
        start_time_text: 'am',
        end_time_text: 'pm',
        in_person_visit: true,
        remote_visit: false,
      },
      session2: {
        timings: '4pm to 8pm',
        in_person_visit: true,
        remote_visit: true,
        start_time: '2:00',
        end_time: '6:00',
        start_time_text: 'pm',
        end_time_text: 'pm',
      },
    },
    {
      day: 'Thursday',
      session1: {
        timings: '9am to 2pm',
        start_time: '9:00',
        end_time: '2:00',
        start_time_text: 'am',
        end_time_text: 'pm',
        in_person_visit: false,
        remote_visit: true,
      },
      session2: {
        timings: '4pm to 8pm',
        in_person_visit: true,
        remote_visit: true,
        start_time: '2:00',
        end_time: '6:00',
        start_time_text: 'pm',
        end_time_text: 'pm',
      },
    },
    {
      day: 'Friday',
      session1: {
        timings: '9am to 2pm',
        start_time: '9:00',
        end_time: '2:00',
        start_time_text: 'am',
        end_time_text: 'pm',
        in_person_visit: false,
        remote_visit: true,
      },
      session2: {
        timings: '4pm to 8pm',
        in_person_visit: true,
        remote_visit: true,
        start_time: '2:00',
        end_time: '6:00',
        start_time_text: 'pm',
        end_time_text: 'pm',
      },
    },
    {
      day: 'Saturday',
      session1: {
        timings: '9am to 2pm',
        start_time: '9:00',
        end_time: '2:00',
        start_time_text: 'am',
        end_time_text: 'pm',
        in_person_visit: false,
        remote_visit: true,
      },
      session2: {
        timings: '4pm to 8pm',
        in_person_visit: true,
        remote_visit: true,
        start_time: '2:00',
        end_time: '6:00',
        start_time_text: 'pm',
        end_time_text: 'pm',
      },
    },
    {
      day: 'Sunday',
      session1: {
        timings: '9am to 2pm',
        start_time: '9:00',
        end_time: '2:00',
        start_time_text: 'am',
        end_time_text: 'pm',
        in_person_visit: true,
        remote_visit: true,
      },
      session2: {
        timings: '4pm to 8pm',
        in_person_visit: false,
        remote_visit: true,
        start_time: '2:00',
        end_time: '6:00',
        start_time_text: 'pm',
        end_time_text: 'pm',
      },
    },
  ],
};

export const leaveAndAbsenceState = {
  from_date: '',
  from_time: '',
  to_date: '',
  to_time: '',
  datePicker: false,
  timePicker: false,
  selected_date: '',
  selected_time: '',
  change_from_date: '',
  change_to_date: '',
  change_from_time: '',
  change_to_time: '',
  modal: false,
  // leave_type_key: '',
  leave_type: '',
  // alert_flag: false,
  reason: '',
  contact: '',
  // appointments: [],
  buttonLoader: false,
  cancelAppointmentLoader: false,
};

export const healphaCallEventEmitter = {
  selectTemplate: 'selectTemplate',
  eventKeyAasha: 'eventKeyAasha',
  eventBacktoConsultation: 'eventBacktoConsultation',
  redial: 'redial',
  eventTwilioDisconnect: 'eventTwilioDisconnect',
  vitalssaved: 'vitalssaved',
  redialcallflagevent: 'redialcallflagevent',
  eventVitals: 'eventVitals',
  eventpushVitalsfromperson: 'eventpushVitalsfromperson',
  eventvitalspushfromdb: 'eventvitalspushfromdb',
  eventaashavalue: 'eventaashavalue',
  eventValueAasha: 'eventValueAasha',
  eventOldPatStartConsultation: 'eventOldPatStartConsultation',
  eventPatientsStartConsultation: 'eventPatientsStartConsultation',
  eventStartConsultation: 'eventStartConsultation',
  getPatientCard: 'getPatientCard',
  updateHomeScreen: 'updateHomeScreen',
  VitalsLabes: 'VitalsLabes',
  toVitals: 'toVitals',
  eventDevicePulse: 'eventDevicePulse',
  eventDeviceBP: 'eventDeviceBP',
  eventDeviceTemp: 'eventDeviceTemp'
}