$RNFirebaseAsStaticFramework = true
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
install! 'cocoapods', :deterministic_uuids => false

target 'healpha_doctor' do


  permissions_path='../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'RNImageToPdf', :path => '../node_modules/react-native-image-to-pdf'
  pod 'rn-fetch-blob',:path => '../node_modules/rn-fetch-blob'
  pod 'react-native-charts-wrapper', :path => '../node_modules/react-native-charts-wrapper' 
  pod 'react-native-location-enabler', :path => '../node_modules/react-native-location-enabler/ios'
  pod 'Firebase/Core', '6.13.0'
  pod 'Firebase/Messaging', '6.13.0'
  pod 'GoogleUtilities', :modular_headers => true

  config = use_native_modules!
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'BEMCheckBox'
  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'
  # pod 'react-native-bluetooth-status', :path => '../node_modules/react-native-bluetooth-status'

  # pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'

  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-twilio-video-webrtc', :path => '../node_modules/react-native-twilio-video-webrtc'
  # pod 'FirebaseCore', :modular_headers => true 
  target 'healpha_doctorTests' do
    inherit! :complete
    # Pods for testing
  end

 
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  # post_install do |installer|
  #   flipper_post_install(installer)

# end


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # use_frameworks! :linkage => :static

  # you should disable the next line.
  use_flipper!()

# target 'healphauser-tvOS' do
 
#     inherit! :search_paths
#     # Pods for testing
#   end
post_install do |installer|
  react_native_post_install(installer)
  __apply_Xcode_12_5_M1_post_install_workaround(installer)
end
end

# target 'healpha_doctor-tvOS' do
#   # Pods for healpha_doctor-tvOS

#     inherit! :search_paths
#     # Pods for testing
#   end


