export const ADD_XP = 'ADD_XP';

export const POST_XP = 'POST_XP';
export const POST_LOAD = 'POST_LOAD';
export const POST_TYPE = 'POST_TYPE';

export const PATIENT_XP = 'PATIENT_XP';
export const PATIENT_LOAD = 'PATIENT_LOAD';
export const PATIENT_FAIL = 'PATIENT_FAIL';

export const NURSING_XP = 'NURSING_XP';

export const CHANGE_XP = 'CHANGE_XP';
export const CHANGE_LOAD = 'CHANGE_LOAD';
export const CHANGE_FAIL = 'CHANGE_FAIL';

export const FORGOT_XP = 'FORGOT_XP';
export const FORGOT_LOAD = 'FORGOT_LOAD';
export const FORGOT_FAIL = 'FORGOT_FAIL';

export const FOR_XP = 'FOR_XP';
export const FOR_LOAD = 'FOR_LOAD';
export const FOR_FAIL = 'FOR_FAIL';

export const TELE_XP = 'TELE_XP';
export const TELE_LOAD = 'TELE_LOAD';
export const TELE_FAIL = 'TELE_FAIL';

export const SAVE_VITALS_SUCCESS = 'SAVE_VITALS_SUCCESS';
export const SAVE_VITALS_LOAD = 'SAVE_VITALS_LOAD';
export const SAVE_VITALS_FAIL = 'SAVE_VITALS_FAIL';
export const GET_VITALS_LABEL = 'GET_VITALS_LABEL';

export const SAVE_SUBJECTIVE_SUCCESS = 'SAVE_SUBJECTIVE_SUCCESS';
export const SAVE_SUBJECTIVE_LOAD = 'SAVE_SUBJECTIVE_LOAD';
export const SAVE_SUBJECTIVE_FAIL = 'SAVE_SUBJECTIVE_FAIL';

export const SAVE_TEMPLATE_SUCCESS = 'SAVE_TEMPLATE_SUCCESS';
export const SAVE_TEMPLATE_LOAD = 'SAVE_TEMPLATE_LOAD';
export const SAVE_TEMPLATE_FAIL = 'SAVE_TEMPLATE_FAIL';

export const SAVE_OBJECTIVE_SUCCESS = 'SAVE_OBJECTIVE_SUCCESS';
export const SAVE_OBJECTIVE_LOAD = 'SAVE_OBJECTIVE_LOAD';
export const SAVE_OBJECTIVE_FAIL = 'SAVE_OBJECTIVE_FAIL';

export const SAVE_ASSESSMENT_SUCCESS = 'SAVE_ASSESSMENT_SUCCESS';
export const SAVE_ASSESSMENT_LOAD = 'SAVE_ASSESSMENT_LOAD';
export const SAVE_ASSESSMENT_FAIL = 'SAVE_ASSESSMENT_FAIL';

export const SAVE_PLAN_SUCCESS = 'SAVE_PLAN_SUCCESS';
export const SAVE_PLAN_LOAD = 'SAVE_PLAN_LOAD';
export const SAVE_PLAN_FAIL = 'SAVE_PLAN_FAIL';

export const CONSULT_XP = 'CONSULT_XP';
export const CONSULT_LOAD = 'CONSULT_LOAD';
export const CONSULT_FAIL = 'CONSULT_FAIL';

export const VALIDATE_XP = 'VALIDATE_XP';
export const VALIDATE_LOAD = 'VALIDATE_LOAD';
export const VALIDATE_FAIL = 'VALIDATE_FAIL';

export const REPORT_XP = 'REPORT_XP';
export const REPORT_LOAD = 'REPORT_LOAD';
export const REPORT_FAIL = 'REPORT_FAIL';

export const OLDPATIENT_XP = 'OLDPATIENT_XP';
export const OLDPATIENT_LOAD = 'OLDPATIENT_LOAD';
export const OLDPATIENT_FAIL = 'OLDPATIENT_FAIL';

export const ENC_XP = 'ENC_XP';
export const ENC_LOAD = 'ENC_LOAD';
export const ENC_FAIL = 'ENC_FAIL';

export const TEMPLET_XP = 'TEMPLET_XP';
export const TEMPLET_LOAD = 'TEMPLET_LOAD';
export const TEMPLET_FAIL = 'TEMPLET_FAIL';
export const TEMPLETID_XP = 'TEMPLETID_XP';

export const APPLY_XP = 'APPLY_XP';
export const APPLY_LOAD = 'APPLY_LOAD';
export const APPLY_FAIL = 'APPLY_FAIL';

export const RETRIEVE_NURSE_VITALS_SUCCESS = 'RETRIEVE_NURSE_VITALS_SUCCESS';
export const RETRIEVE_NURSE_VITALS_LOAD = 'RETRIEVE_NURSE_VITALS_LOAD';
export const RETRIEVE_NURSE_VITALS_FAIL = 'RETRIEVE_NURSE_VITALS_FAIL';

export const DOCTOR_XP = 'DOCTOR_XP';
export const DOCTOR_LOAD = 'DOCTOR_LOAD';
export const DOCTOR_FAIL = 'DOCTOR_FAIL';

export const MEDICINE_XP = 'MEDICINE_XP';
export const MEDICINE_LOAD = 'MEDICINE_LOAD';
export const MEDICINE_FAIL = 'MEDICINE_FAIL';

export const MEDICINE1_XP = 'MEDICINE1_XP';
export const MEDICINE1_LOAD = 'MEDICINE1_LOAD';
export const MEDICINE1_FAIL = 'MEDICINE1_FAIL';

export const ADDMED_XP = 'ADDMED_XP';
export const ADDMED_LOAD = 'ADDMED_LOAD';
export const ADDMED_FAIL = 'ADDMED_FAIL';

export const ADDMED1_XP = 'ADDMED1_XP';
export const ADDMED1_LOAD = 'ADDMED1_LOAD';
export const ADDMED1_FAIL = 'ADDMED1_FAIL';

export const DELMED1_XP = 'DELMED1_XP';
export const DELMED1_LOAD = 'DELMED1_LOAD';
export const DELMED1_FAIL = 'DELMED1_FAIL';

export const DELMED_XP = 'DELMED_XP';
export const DELMED_LOAD = 'DELMED_LOAD';
export const DELMED_FAIL = 'DELMED_FAIL';

export const SERVICES_SUCCESS = 'SERVICES_SUCCESS';
export const SERVICES_LOAD = 'SERVICES_LOAD';
export const SERVICES_FAIL = 'SERVICES_FAIL';

export const SAVE_LAB_SUCCESS = 'SAVE_LAB_SUCCESS';
export const SAVE_LAB_LOAD = 'SAVE_LAB_LOAD';
export const SAVE_LAB_FAIL = 'SAVE_LAB_FAIL';

export const SAVE_IMG_ORDER_SUCCESS = 'SAVE_IMG_ORDER_SUCCESS';
export const SAVE_IMG_ORDER_LOAD = 'SAVE_IMG_ORDER_LOAD';
export const SAVE_IMG_ORDER_FAIL = 'SAVE_IMG_ORDER_FAIL';

export const SAVE_NURSING_ORDER_SUCCESS = 'SAVE_NURSING_ORDER_SUCCESS';
export const SAVE_NURSING_ORDER_LOAD = 'SAVE_NURSING_ORDER_LOAD';
export const SAVE_NURSING_ORDER_FAIL = 'SAVE_NURSING_ORDER_FAIL';

export const SAVE_VACCINE_ORDER_SUCCESS = 'SAVE_VACCINE_ORDER_SUCCESS';
export const SAVE_VACCINE_ORDER_LOAD = 'SAVE_VACCINE_ORDER_LOAD';
export const SAVE_VACCINE_ORDER_FAIL = 'SAVE_VACCINE_ORDER_FAIL';

export const DELETE_LAB_SUCCESS = 'DELETE_LAB_SUCCESS';
export const DELETE_LAB_LOAD = 'DELETE_LAB_LOAD';
export const DELETE_LAB_FAIL = 'DELETE_LAB_FAIL';

export const DELETE_IMG_ORDER_SUCCESS = 'DELETE_IMG_ORDER_SUCCESS';
export const DELETE_IMG_ORDER_LOAD = 'DELETE_IMG_ORDER_LOAD';
export const DELETE_IMG_ORDER_FAIL = 'DELETE_IMG_ORDER_FAIL';

export const DELETE_NURSING_ORDER_SUCCESS = 'DELETE_NURSING_ORDER_SUCCESS';
export const DELETE_NURSING_ORDER_LOAD = 'DELETE_NURSING_ORDER_LOAD';
export const DELETE_NURSING_ORDER_FAIL = 'DELETE_NURSING_ORDER_FAIL';

export const DELETE_VACCINE_ORDER_SUCCESS = 'DELETE_VACCINE_ORDER_SUCCESS';
export const DELETE_VACCINE_ORDER_LOAD = 'DELETE_VACCINE_ORDER_LOAD';
export const DELETE_VACCINE_ORDER_FAIL = 'DELETE_VACCINE_ORDER_FAIL';

export const RETRIEVE_PERSON_TIMELINE_SUCCESS =
  'RETRIEVE_PERSON_TIMELINE_SUCCESS';
export const RETRIEVE_PERSON_TIMELINE_LOAD = 'RETRIEVE_PERSON_TIMELINE_LOAD';
export const RETRIEVE_PERSON_TIMELINE_FAIL = 'RETRIEVE_PERSON_TIMELINE_FAIL';

export const RETRIEVE_VACCINE_ORDER_SUCCESS = 'RETRIEVE_VACCINE_ORDER_SUCCESS';
export const RETRIEVE_VACCINE_ORDER_LOAD = 'RETRIEVE_VACCINE_ORDER_LOAD';
export const RETRIEVE_VACCINE_ORDER_FAIL = 'RETRIEVE_VACCINE_ORDER_FAIL';

export const REPEAT_LAB_SUCCESS = 'REPEAT_LAB_SUCCESS';
export const REPEAT_LAB_LOAD = 'REPEAT_LAB_LOAD';
export const REPEAT_LAB_FAIL = 'REPEAT_LAB_FAIL';

export const REPEAT_ALL_LAB_SUCCESS = 'REPEAT_ALL_LAB_SUCCESS';
export const REPEAT_ALL_LAB_LOAD = 'REPEAT_ALL_LAB_LOAD';
export const REPEAT_ALL_LAB_FAIL = 'REPEAT_ALL_LAB_FAIL';

export const REPEAT_IMAGING_SUCCESS = 'REPEAT_IMAGING_SUCCESS';
export const REPEAT_IMAGING_LOAD = 'REPEAT_IMAGING_LOAD';
export const REPEAT_IMAGING_FAIL = 'REPEAT_IMAGING_FAIL';

export const REPEAT_ALL_IMAGING_SUCCESS = 'REPEAT_ALL_IMAGING_SUCCESS';
export const REPEAT_ALL_IMAGING_LOAD = 'REPEAT_ALL_IMAGING_LOAD';
export const REPEAT_ALL_IMAGING_FAIL = 'REPEAT_ALL_IMAGING_FAIL';

export const PRESEC_XP = 'PRESEC_XP';
export const PRESEC_LOAD = 'PRESEC_LOAD';
export const PRESEC_FAIL = 'PRESEC_FAIL';

export const IMMUN_XP = 'IMMUN_XP';
export const IMMUN_LOAD = 'IMMUN_LOAD';
export const IMMUN_FAIL = 'IMMUN_FAIL';

export const IMMUN1_XP = 'IMMUN1_XP';
export const IMMUN1_LOAD = 'IMMUN1_LOAD';
export const IMMUN1_FAIL = 'IMMUN1_FAIL';

export const IMMUN2_XP = 'IMMUN2_XP';
export const IMMUN2_LOAD = 'IMMUN2_LOAD';
export const IMMUN2_FAIL = 'IMMUN2_FAIL';

export const GCHART_XP = 'GCHART_XP';
export const GCHART_LOAD = 'GCHART_LOAD';
export const GCHART_FAIL = 'GCHART_FAIL';

export const TIME_XP = 'TIME_XP';
export const TIME_LOAD = 'TIME_LOAD';
export const TIME_FAIL = 'TIME_FAIL';

export const HISTORY_XP = 'HISTORY_XP';
export const HISTORY_LOAD = 'HISTORY_LOAD';
export const HISTORY_FAIL = 'HISTORY_FAIL';

export const ADD_ALLERGY_XP = 'ADD_ALLERGY_XP';
export const ADD_ALLERGY_LOAD = 'ADD_ALLERGY_LOAD';
export const ADD_ALLERGY_FAIL = 'ADD_ALLERGY_FAIL';

export const DELETE_ALLERGY_XP = 'DELETE_ALLERGY_XP';
export const DELETE_ALLERGY_LOAD = 'DELETE_ALLERGY_LOAD';
export const DELETE_ALLERGY_FAIL = 'DELETE_ALLERGY_FAIL';

export const ADD_SSM_XP = 'ADD_SSM_XP';
export const ADD_SSM_LOAD = 'ADD_SSM_LOAD';
export const ADD_SSM_FAIL = 'ADD_SSM_FAIL';

export const UPDATE_ALLERGY_XP = 'UPDATE_ALLERGY_XP';
export const UPDATE_ALLERGY_LOAD = 'UPDATE_ALLERGY_LOAD';
export const UPDATE_ALLERGY_FAIL = 'UPDATE_ALLERGY_FAIL';

export const NON_XP = 'NON_XP';
export const NON_LOAD = 'NON_LOAD';
export const NON_FAIL = 'NON_FAIL';
export const UPDATEMS_XP = 'UPDATEMS_XP';
export const UPDATEMS_LOAD = 'UPDATEMS_LOAD';
export const UPDATEMS_FAIL = 'UPDATEMS_FAIL';

export const DELETE_TEMP_MEDICINE_SUCCESS = 'DELETE_TEMP_MEDICINE_SUCCESS';
export const DELETE_TEMP_MEDICINE_LOAD = 'DELETE_TEMP_MEDICINE_LOAD';
export const DELETE_TEMP_MEDICINE_FAIL = 'DELETE_TEMP_MEDICINE_FAIL';

export const DELETE_TEMP_SUPPLEMENT_SUCCESS = 'DELETE_TEMP_SUPPLEMENT_SUCCESS';
export const DELETE_TEMP_SUPPLEMENT_LOAD = 'DELETE_TEMP_SUPPLEMENT_LOAD';
export const DELETE_TEMP_SUPPLEMENT_FAIL = 'DELETE_TEMP_SUPPLEMENT_FAIL';

export const DELETE_TEMP_LAB_SUCCESS = 'DELETE_TEMP_LAB_SUCCESS';
export const DELETE_TEMP_LAB_LOAD = 'DELETE_TEMP_LAB_LOAD';
export const DELETE_TEMP_LAB_FAIL = 'DELETE_TEMP_LAB_FAIL';

export const DELETE_TEMP_IMG_SUCCESS = 'DELETE_TEMP_IMG_SUCCESS';
export const DELETE_TEMP_IMG_LOAD = 'DELETE_TEMP_IMG_LOAD';
export const DELETE_TEMP_IMG_FAIL = 'DELETE_TEMP_IMG_FAIL';

export const DELETE_TEMP_NURSING_SUCCESS = 'DELETE_TEMP_NURSING_SUCCESS';
export const DELETE_TEMP_NURSING_LOAD = 'DELETE_TEMP_NURSING_LOAD';
export const DELETE_TEMP_NURSING_FAIL = 'DELETE_TEMP_NURSING_FAIL';

export const CHANGE_TAB_SUCCESS = 'CHANGE_TAB_SUCCESS';
export const CHANGE_TAB_LOAD = 'CHANGE_TAB_LOAD';
export const CHANGE_TAB_FAIL = 'CHANGE_TAB_FAIL';

export const UPDATE_VACCINEBATCH_SUCCESS = 'UPDATE_VACCINEBATCH_SUCCESS';
export const UPDATE_VACCINEBATCH_LOAD = 'UPDATE_VACCINEBATCH_LOAD';
export const UPDATE_VACCINEBATCH_FAIL = 'UPDATE_VACCINEBATCH_FAIL';

export const GET_PRACTICE_BRANCH_LOAD = 'GET_PRACTICE_BRANCH_LOAD';
export const GET_PRACTICE_BRANCH_SUCCESS = 'GET_PRACTICE_BRANCH_SUCCESS';
export const GET_PRACTICE_BRANCH_FAIL = 'GET_PRACTICE_BRANCH_FAIL';

export const GET_DOCTOR_LOAD = 'GET_DOCTOR_LOAD';
export const GET_DOCTOR_SUCCESS = 'GET_DOCTOR_SUCCESS';
export const GET_DOCTOR_FAIL = 'GET_DOCTOR_FAIL';

export const GET_COVID_MONITOR_COUNT_LOAD = 'GET_COVID_MONITOR_COUNT_LOAD';
export const GET_COVID_MONITOR_COUNT_SUCCESS =
  'GET_COVID_MONITOR_COUNT_SUCCESS';
export const GET_COVID_MONITOR_COUNT_FAIL = 'GET_COVID_MONITOR_COUNT_FAIL';

export const GET_COVID_MONITOR_LIST_LOAD = 'GET_COVID_MONITOR_LIST_LOAD';
export const GET_COVID_MONITOR_LIST_SUCCESS = 'GET_COVID_MONITOR_LIST_SUCCESS';
export const GET_COVID_MONITOR_LIST_FAIL = 'GET_COVID_MONITOR_LIST_FAIL';

export const GET_COVID_MONITOR_PATIENT_LOAD = 'GET_COVID_MONITOR_PATIENT_LOAD';
export const GET_COVID_MONITOR_PATIENT_SUCCESS =
  'GET_COVID_MONITOR_PATIENT_SUCCESS';
export const GET_COVID_MONITOR_PATIENT_FAIL = 'GET_COVID_MONITOR_PATIENT_FAIL';

export const GET_COVID_NOTES_LOAD = 'GET_COVID_NOTES_LOAD';
export const GET_COVID_NOTES_SUCCESS = 'GET_COVID_NOTES_SUCCESS';
export const GET_COVID_NOTES_FAIL = 'GET_COVID_NOTES_FAIL';

export const GET_STANDARD_NOTES_LOAD = 'GET_STANDARD_NOTES_LOAD';
export const GET_STANDARD_NOTES_SUCCESS = 'GET_STANDARD_NOTES_SUCCESS';
export const GET_STANDARD_NOTES_FAIL = 'GET_STANDARD_NOTES_FAIL';

export const SAVE_COVID_NOTES_DATA_LOAD = 'SAVE_COVID_NOTES_DATA_LOAD';
export const SAVE_COVID_NOTES_DATA_SUCCESS = 'SAVE_COVID_NOTES_DATA_SUCCESS';
export const SAVE_COVID_NOTES_DATA_FAIL = 'SAVE_COVID_NOTES_DATA_FAIL';

export const CLOSE_ENCOUNTER_STATUS_LOAD = 'CLOSE_ENCOUNTER_STATUS_LOAD';
export const CLOSE_ENCOUNTER_STATUS_SUCCESS = 'CLOSE_ENCOUNTER_STATUS_SUCCESS';
export const CLOSE_ENCOUNTER_STATUS_FAIL = 'CLOSE_ENCOUNTER_STATUS_FAIL';

export const REOPEN_ENCOUNTER_STATUS_LOAD = 'REOPEN_ENCOUNTER_STATUS_LOAD';
export const REOPEN_ENCOUNTER_STATUS_SUCCESS =
  'REOPEN_ENCOUNTER_STATUS_SUCCESS';
export const REOPEN_ENCOUNTER_STATUS_FAIL = 'REOPEN_ENCOUNTER_STATUS_FAIL';

export const SAVE_PATIENT_CONSENT_LOAD = 'SAVE_PATIENT_CONSENT_LOAD';
export const SAVE_PATIENT_CONSENT_SUCCESS = 'SAVE_PATIENT_CONSENT_SUCCESS';
export const SAVE_PATIENT_CONSENT_FAIL = 'SAVE_PATIENT_CONSENT_FAIL';

export const TWILIO_DATA_CHANNEL_XP = 'TWILIO_DATA_CHANNEL_XP';
export const TWILIO_DATA_CHANNEL_LOAD = 'TWILIO_DATA_CHANNEL_LOAD';
export const TWILIO_DATA_CHANNEL_FAIL = 'TWILIO_DATA_CHANNEL_FAIL';

export const RANDOM_XP = 'RANDOM_XP';
export const RANDOM_LOAD = 'RANDOM_LOAD';
export const RANDOM_FAIL = 'RANDOM_FAIL';
