export const environment = {
  API_URL: 'https://core.dev.healpha.com/',
  environmentType: 'dev',
  development_url: 'https://core.dev.healpha.com/data',
  base_url: 'https://core.dev.healpha.com/api/',
  currency_symbol: '₹',
  currency_name: 'rupee',
  payment_gate_way: 'razorpay',
  sms_provider: 'bash',
  languages: [
    {id: 1, label: 'English', value: 'en'},
    {id: 2, label: 'हिंदी', value: 'hi'},
    {id: 3, label: 'తెలుగు', value: 'te'},
  ],
  country_code: '+91',
  instanceType: 'coreDev',
  timezone:'Asia/Kolkata'
  // email_provider: '',
  // country_label: 'country',
  // state_label: 'state',
  // city_label: 'city',
  // date_format: 'dd/mm/yy',
  // time_format: 'hh:mm',
  // country_code: '',
  // time_zone: '',
};
