import {StyleSheet, StatusBar, Platform} from 'react-native';
import {wp} from '../../../themes/Scale';
import {theme} from '../../../themes/Theme';
import {
  DEFAULT_GREY_COLOR,
  DEFAULT_WHITE_COLOR,
  TWILIO_CALL_BUTTON_COLOR,
  APP_PRIMARY_COLOR,
  DEFAULT_RED_COLOR,
  DEFAULT_GREEN_COLOR,
} from '../../../themes/variable';
const STATUSBAR_HEIGHT = StatusBar.currentHeight;
export default StyleSheet.create({
  flex: {
    flex: 1,
  },
  statusBar: {
    height: STATUSBAR_HEIGHT,
  },
  stethFlex: {
    flex: 1,
    flexDirection: 'row',
  },
  connectedUserView: {
    height: wp(80),
    width: wp(80),
    borderRadius: wp(80),
    borderWidth: 1,
    borderColor: '#FFEDED',
    backgroundColor: '#FFEDED',
    marginLeft: wp(5),
    marginRight: wp(5),
  },
  itemsCenter: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  connectedPersonText: {
    color: '#FF6060',
    fontSize: theme.fontSizes.xl,
    fontFamily: theme.fontFamily.primaryRegular,
  },
  localVideoView: {
    height: '55%',
    padding: wp(20),
    paddingBottom: 0,
    borderRadius: wp(10),
  },
  videoContentView: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    paddingBottom: wp(20),
  },
  connectedText: {
    color: DEFAULT_WHITE_COLOR,
    fontSize: theme.fontSizes.md,
    fontFamily: theme.fontFamily.primaryRegular,
  },
  TwilioVideoLocalView: {
    flex: 1,
    zIndex: 2,
  },
  participateConnectionView: {
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    height: '20%',
    margin: wp(20),
    marginTop: 0,
    marginBottom: 0,
    flexDirection: 'row',
  },
  flexDirection: {
    flexDirection: 'row',
  },
  marginTop18: {
    marginTop: wp(18),
  },
  marginRight10: {
    marginRight: wp(10),
  },
  twilioBackgroundColor: {
    backgroundColor: '#1A3A44',
  },
  twilioMainFloatingView: {
    position: 'absolute',
    right: wp(10),
    bottom: wp(10),
    width: wp(200),
    height: wp(200),
    zIndex: 100,
    borderRadius: wp(20),
  },
  twilioMainWindow: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: 100,
  },
  localVideoMargin: {
    // margin: wp(10),
  },
  itemsCenterAndEnd: {
    justifyContent: 'center',
    alignContent: 'flex-end',
    alignItems: 'flex-end',
  },
  flex15: {
    flex: 1.5,
  },
  paddingZero: {
    padding: 0,
  },
  floatingLocalVideo: {
    height: '90%',
  },
  heightZero: {
    height: '0%',
  },
  marginZero: {
    margin: 0,
  },
  paddingBottomZero: {
    paddingBottom: 0,
  },
  maximizeIcon: {
    height: wp(18),
    width: wp(18),
    marginTop: wp(5),
    marginBottom: wp(5),
  },
  displayNone: {
    display: 'none',
  },
  displayFlex: {
    display: 'flex',
  },
  twilioButtonMainView: {
    position: 'absolute',
    left: 0,
    bottom: Platform.OS === 'ios' ? 70 : 50,
    right: 0,
    height: wp(100),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignContent: 'center',
    // justifyContent: 'space-evenly',
  },
  zIndex0: {
    zIndex: 0,
  },
  zIndex2: {
    zIndex: 2,
  },
  micButtonStyles: {
    width: wp(75),
    height: wp(45),
    marginLeft: wp(10),
    marginRight: wp(10),
    borderRadius: wp(10),
    // borderRadius: wp(100) / 2,
    backgroundColor: TWILIO_CALL_BUTTON_COLOR,
    justifyContent: 'center',
    alignItems: 'center',
  },
  flex3: {
    flex: 3,
  },
  marginLeft45: {
    marginLeft: wp(45),
  },
  itemsEnd: {
    justifyContent: 'flex-end',
    alignContent: 'center',
    alignItems: 'flex-end',
  },
  stethoscopeIcon: {
    height: wp(22),
    width: wp(22),
  },
  dialingPatientText: {
    margin: wp(20),
    fontSize: theme.fontSizes.lg,
    color: DEFAULT_WHITE_COLOR,
    justifyContent: 'flex-end',
    alignContent: 'center',
    alignItems: 'flex-end',
  },
  dialingPatientMainView: {
    borderRadius: wp(16),
    flexShrink: 0,
    overflow: 'hidden',
    width: '80%',
    height: '85%',
    backgroundColor: '#E64C4C',
  },
  connectingPatientNameView: {
    position: 'absolute',
    zIndex: 100,
    overflow: 'visible',
    width: '100%',
    bottom: 0,
    padding: wp(15),
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  nameText: {
    color: DEFAULT_WHITE_COLOR,
    fontSize: theme.fontSizes.md,
    paddingLeft: wp(10),
  },
  connectingPatientName: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    flex: 1,
    marginTop: wp(-30),
  },
  PatientNameText: {
    color: DEFAULT_WHITE_COLOR,
    fontSize: theme.fontSizes.vxxxl,
  },
  itemsEndAndFlex2: {
    flex: 2,
    justifyContent: 'flex-end',
    alignContent: 'flex-end',
    alignItems: 'flex-end',
    flexDirection: 'row',
  },
  connectedCircle: {
    margin: wp(20),
    fontSize: theme.fontSizes.lg,
    marginRight: wp(-18),
  },
  connected: {
    margin: wp(20),
    fontSize: theme.fontSizes.lg,
    color: DEFAULT_WHITE_COLOR,
  },
  contentEnd: {
    flex: 1,
    alignContent: 'flex-end',
    alignItems: 'flex-end',
    marginTop: Platform.OS === 'ios' ? 20 : 0,
  },
  participateMainView: {
    borderRadius: wp(16),
    flexShrink: 0,
    overflow: 'hidden',
    width: '100%',
    height: '85%',
    backgroundColor: '#E64C4C',
  },
  height: {
    height: '100%',
  },
  participateMediaView: {
    position: 'absolute',
    zIndex: 100,
    overflow: 'visible',
    width: '100%',
    flexDirection: 'row',
    padding: wp(10),
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
  },
  justifyContentCenter: {
    justifyContent: 'center',
  },
  ptMediaView: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    alignContent: 'flex-end',
    flexDirection: 'row',
  },
  ptMediaTouch: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: wp(5),
    borderRadius: wp(8),
    marginLeft: wp(3),
    marginRight: wp(3),
  },
  ptNameView: {
    position: 'absolute',
    zIndex: 100,
    overflow: 'visible',
    width: '100%',
    bottom: 0,
    padding: wp(7),
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  ptName: {
    color: DEFAULT_WHITE_COLOR,
    fontSize: theme.fontSizes.md,
    padding: wp(8),
  },
  twilioVideoParticipantView: {
    backgroundColor: '#dedede',
    borderRadius: wp(16),
    bottom: 0,
    height: '100%',
    left: 0,
    resizeMode: 'cover',
    right: 0,
    top: 0,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  lcVideoMainView: {
    width: '100%',
    height: '23%',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    flexDirection: 'row',
    marginTop: wp(40),
  },
  lcVideoHidden: {
    borderRadius: wp(25),
    flexShrink: 0,
    overflow: 'hidden',
    width: '40%',
    height: '100%',
    marginLeft: wp(5),
    marginRight: wp(5),
  },
  lcVideoNameView: {
    position: 'absolute',
    zIndex: 100,
    overflow: 'visible',
    width: '100%',
    bottom: 0,
    padding: wp(7),
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  lcVideoName: {
    color: DEFAULT_WHITE_COLOR,
    fontSize: theme.fontSizes.sm,
    paddingLeft: wp(10),
  },
  twilioVideoLocalView: {
    backgroundColor: '#dedede',
    borderRadius: wp(16),
    bottom: 0,
    height: '100%',
    left: 0,
    resizeMode: 'cover',
    right: 0,
    top: 0,
    width: '100%',
  },
  optMainView: {
    borderRadius: wp(25),
    flexShrink: 0,
    overflow: 'hidden',
    width: '40%',
    height: '100%',
    marginLeft: wp(5),
    marginRight: wp(5),
  },
  optNameView: {
    position: 'absolute',
    zIndex: 100,
    overflow: 'visible',
    width: '100%',
    bottom: 0,
    padding: wp(7),
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  optNameText: {
    color: DEFAULT_WHITE_COLOR,
    fontSize: theme.fontSizes.sm,
    paddingLeft: wp(10),
  },
  optMediaView: {
    position: 'absolute',
    zIndex: 100,
    overflow: 'visible',
    width: '100%',
    padding: wp(7),
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  optVideo: {
    backgroundColor: '#dedede',
    borderRadius: wp(16),
    bottom: 0,
    height: '100%',
    left: 0,
    resizeMode: 'cover',
    right: 0,
    top: 0,
    width: '100%',
  },
  bgTransparent: {
    backgroundColor: 'transparent',
  },
  justifyContentSpaceAround: {
    justifyContent: 'space-around',
  },
  mediaOnOff: {
    color: DEFAULT_WHITE_COLOR,
    fontSize: theme.fontSizes.sm,
  },
  updateText: {
    fontSize: theme.fontSizes.md,
    color: DEFAULT_WHITE_COLOR,
    fontFamily: theme.fontFamily.primarySemiBold,
  },
  buttonStyles: {
    width: '90%',
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    height: '90%',
    elevation: 0,
    borderRadius: wp(6),
    backgroundColor: APP_PRIMARY_COLOR,
    marginTop: 10,
  },
  ptFullScreenTouch: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: wp(2),
    borderRadius: wp(8),
    marginLeft: wp(3),
    marginRight: wp(3),
  },
  fullScreen: {
    position: 'absolute',
    zIndex: 100,
    overflow: 'visible',
    width: '100%',
    flexDirection: 'row',
    top: wp(15),
    right: wp(15),
    justifyContent: 'flex-end',
  },
  hideCallingMainView: {
    height: wp(40),
    width: wp(40),
    backgroundColor: DEFAULT_RED_COLOR,
    borderRadius: wp(10),
    position: 'absolute',
    zIndex: 100,
    overflow: 'visible',
    borderWidth: 1,
    borderColor: DEFAULT_WHITE_COLOR,
  },
  hideCallingTouchableView: {
    height: '100%',
    width: '100%',
    position: 'absolute',
    zIndex: 100,
    overflow: 'visible',
  },
  activeButton: {
    height: wp(10),
    width: wp(10),
    position: 'absolute',
    zIndex: 100,
    top: 0,
    right: 0,
    justifyContent: 'flex-end',
    backgroundColor: DEFAULT_GREEN_COLOR,
    borderRadius: 50,
  },
  hideNameText: {
    color: DEFAULT_WHITE_COLOR,
    fontSize: theme.fontSizes.md,
  },
  itemsStart: {
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
    alignItems: 'flex-start',
  },
  minimizeCall: {
    position: 'absolute',
    right: wp(2),
    top: wp(2),
    width: wp(20),
    height: wp(20),
    zIndex: 100,
    borderRadius: wp(15),
  },
  hideCallView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
});
